# ç«™ç‚¹æ ‡é¢˜
site_name: Infinite Space

# ç«™ç‚¹URL
site_url: https://finneganwx.github.io/infinite-space
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes - searchable, customizable, in 60+ languages, for all devices

# å…³è”è¿œç¨‹ä»“åº“
repo_url: https://github.com/finneganwx/infinite-space
repo_name: finneganwx/infinite-space

# ç‰ˆæƒå£°æ˜
copyright: Copyright &copy; 2022 - 2023 Finn

# å¯¼èˆª
nav:
    - ğŸ§‘â€ğŸ’» Home: 'index.md'

    - ğŸ“ Blog: 
      - Blog: 'blog/index.md'

    - ğŸ“Œ HandBook:
      - Gitå¸¸ç”¨æ“ä½œ: 'handbook/git.md'

    - ğŸ» OpenSource:
      - VHIP-EASYBUILD-API: 
        - Tutorial:
          - Install && Import: 'myos/vhip/tutorial/install&import.md'
          - Eaxmple: 'myos/vhip/tutorial/example.md'
        - API: 
          - Intro: 'myos/vhip/api/index.md'
          - Build: 'myos/vhip/api/build.md'
          - Print: 'myos/vhip/api/print.md'
          - Assist: 'myos/vhip/api/assist.md'
          - Util: 'myos/vhip/api/util.md'
        

    - âœ¨ Notes:
      - C#: 
        - è®¤è¯† C#: 'teches/csharp/00-è®¤è¯†CSharp.md'
        - æ•°æ®ç±»å‹: 'teches/csharp/01-æ•°æ®ç±»å‹.md'
        - è¿ç®—ç¬¦: 'teches/csharp/02-è¿ç®—ç¬¦.md'
        - æ§åˆ¶è¯­å¥: 'teches/csharp/03-æ§åˆ¶è¯­å¥.md'
        - æ•°æ®ç»“æ„: 'teches/csharp/04-æ•°æ®ç»“æ„.md'
        - ç±»ä¸å¯¹è±¡: 'teches/csharp/05-ç±»ä¸å¯¹è±¡.md'
        - æŠ½è±¡ç±»ä¸æ¥å£: 'teches/csharp/06-æŠ½è±¡ç±»ä¸æ¥å£.md'
        - å¼‚å¸¸å¤„ç†: 'teches/csharp/07-å¼‚å¸¸å¤„ç†.md'
        - å¸¸ç”¨ç±»: 'teches/csharp/08-å¸¸ç”¨ç±».md'
        - ç´¢å¼•å™¨: 'teches/csharp/09-ç´¢å¼•å™¨.md'
        - å§”æ‰˜: 'teches/csharp/10-å§”æ‰˜ä¸äº‹ä»¶.md'
        - æ³›å‹: 'teches/csharp/11-æ³›å‹.md'
        - é›†åˆ: 'teches/csharp/12-é›†åˆ.md'
        - ç‰¹æ€§: 'teches/csharp/13-ç‰¹æ€§.md'
        - åå°„: 'teches/csharp/14-åå°„.md'
        - å¤šçº¿ç¨‹: 'teches/csharp/15-å¤šçº¿ç¨‹.md'
        - æ–‡ä»¶å¤„ç†: 'teches/csharp/16-æ–‡ä»¶å¤„ç†.md'
        # - åŒ¿åå‡½æ•°: teches/csharp/
        # - æŒ‡é’ˆå˜é‡: teches/csharp/

      - LINQ:
        - è®¤è¯† LINQ: 'teches/linq/01-è®¤è¯†LINQ.md'
        - æŸ¥è¯¢è¯­æ³•: 'teches/linq/02-æŸ¥è¯¢è¯­æ³•.md'
        - æ–¹æ³•è¯­æ³•: 'teches/linq/03-æ–¹æ³•è¯­æ³•.md'
        - æ ‡å‡†æŸ¥è¯¢è¿ç®—ç¬¦: 
          - æ ‡å‡†æŸ¥è¯¢è¿ç®—ç¬¦æ–¹æ³•: 'teches/linq/04-æ ‡å‡†æŸ¥è¯¢è¿ç®—ç¬¦æ–¹æ³•.md'
          - æŠ•å½±è¿ç®—: 'teches/linq/05-æŠ•å½±è¿ç®—.md'
          - ç­›é€‰è¿ç®—: 'teches/linq/06-ç­›é€‰è¿ç®—.md'
          - æ’åºè¿ç®—: 'teches/linq/07-æ’åºè¿ç®—.md'
          - æ•°æ®åˆ†ç»„: 'teches/linq/08-æ•°æ®åˆ†ç»„.md'

      - ADO.NET:
        - è®¤è¯† ADO.NET: 'teches/adonet/01-è®¤è¯†ADO.NET.md'
        - æ•°æ®æä¾›ç¨‹åº: 'teches/adonet/02-æ•°æ®æä¾›ç¨‹åº.md'
        - æ•°æ®é›†: 'teches/adonet/03-æ•°æ®é›†.md'
        - æ•°æ®ç±»å‹æ˜ å°„: 'teches/adonet/04-æ•°æ®ç±»å‹æ˜ å°„.md'
        - è¿æ¥æ•°æ®æº: 'teches/adonet/05-è¿æ¥æ•°æ®æº.md'
        - åˆ›å»ºå‘½ä»¤ä¸é…ç½®å‚æ•°: 'teches/adonet/06-åˆ›å»ºå‘½ä»¤ä¸é…ç½®å‚æ•°.md'
        - æ£€ç´¢å’Œä¿®æ”¹æ•°æ®: 'teches/adonet/07-æ£€ç´¢å’Œä¿®æ”¹æ•°æ®.md'
        - äº‹åŠ¡ä¸å¹¶å‘æ€§: 'teches/adonet/08-äº‹åŠ¡ä¸å¹¶å‘æ€§.md'

    - ğŸ¤¡ About: 
      - Author: 'common/author.md'
      - MkDocs: 'common/mkdocs.md'

# ä¸»é¢˜è®¾ç½®
theme:
  name: material
  
  logo: assets/favicon.ico

  # æµè§ˆå™¨æ ‡ç­¾é¡µå›¾æ ‡
  favicon: assets/favicon.ico

  # è¯­è¨€ è‹±æ–‡ï¼šlanguage: en
  language: zh

  font:
    text: Consolas

  # å›¾æ ‡
  icon:
    # logo: material/library
    repo: fontawesome/brands/github

  
  # æ ‡é¢˜æ 
  features:
    # å¯¼èˆªé€‰é¡¹å¡
    - navigation.tabs
    - navigation.sections
    # è¿”å›é¡¶éƒ¨
    - navigation.top
    # ç›®å½•è·Ÿéš
    - toc.follow
    # ä»£ç å—å¤åˆ¶
    - content.code.copy
    # ä»£ç æ³¨é‡Š
    - content.code.annotate
    # Improved tooltips
    - content.tooltips
    # æ ‡é¢˜æ ç§»åŠ¨éšè—
    # - header.autohide
    # AjaxåŠ è½½ï¼Œå¤§å‹ç½‘ç«™å¯å¼€å¯
    # - navigation.instant
    # URLé”šç‚¹è·Ÿè¸ª
    - navigation.tracking
    # footer é¡µé¢åº•éƒ¨
    - navigation.footer

  # è°ƒè‰²æ¿
  palette: 
    # light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

# é™„åŠ ç»„ä»¶
extra:
  # ç¤¾äº¤
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/698590186?spm_id_from=333.1007.0.0
      name: BiliBili

    - icon: fontawesome/brands/weibo
      link: https://github.com/finneganwill/material-csharp
      name: å¾®åš

  # åˆ†æ
  analytics: 
    # åˆ†æå™¨
    provider: google
    property: G-XXXXXXXXXX

    # åé¦ˆè®¾ç½®
    feedback:
      title: æœ¬æ–‡ç« å¯¹æ‚¨æ˜¯å¦æœ‰å¸®åŠ©ï¼Ÿ
      ratings:
        - icon: material/emoticon-happy-outline
          name: æ„Ÿè°¢å¸®åŠ©ï¼
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: æœ‰å¾…æå‡ï¼
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="" target="_blank" rel="noopener">feedback form</a>.

# MDæ‰©å±•
markdown_extensions:
  # è„šæ³¨
  - footnotes
  # ä»£ç é«˜äº®
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # æç¤ºä¸è­¦å‘Š
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # æ–‡æœ¬æ ‡è®°ï¼šä¸‹åˆ’çº¿ï¼Œé«˜äº®ï¼Œåˆ é™¤ï¼Œæ·»åŠ ç­‰
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # å†…å®¹é€‰é¡¹å¡
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


  # ç›®å½•
  - toc:
      # æ®µè½é”šé“¾æ¥ç¬¦å·
      permalink: âš“ï¸
      # ç›®å½•æ·±åº¦
      toc_depth: 3

      # é”šé“¾æ¥è¯´æ˜
      # permalink_title: Anchor link to this section for reference
      # æ ‡é¢˜
      # title: Content

  # ç½‘æ ¼
  - attr_list
  - md_in_html

  # åˆ—è¡¨
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true




# æ’ä»¶
plugins:
  # åšå®¢æ’ä»¶
  - blog:
      blog_toc: false

      archive: true
      archive_name: Archive
      archive_toc: true

      categories: true
      categories_name: Categories
      categories_toc: true

      authors: true
      authors_file: '{blog}/.authors.yml'

      pagination_per_page: 5

  # æœç´¢æ’ä»¶
  - search

  # æ—¶é—´æ’ä»¶
  # pip install mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true

  # å›¾åƒç¼©æ”¾æ’ä»¶
  # pip install mkdocs-glightbox
  - glightbox

  # - social

  # - privacy

